# Generated by Django 3.1.3 on 2020-11-27 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 11, 27, 20, 16, 38, 822081)),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 11, 27, 20, 16, 38, 822717)),
        ),
    ]
