# Generated by Django 3.1.3 on 2020-11-27 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201127_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 11, 27, 20, 16, 45, 262992)),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 11, 27, 20, 16, 45, 263677)),
        ),
    ]
