# Generated by Django 3.1.3 on 2020-11-27 12:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201127_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 11, 27, 20, 25, 13, 234780)),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 11, 27, 20, 25, 13, 235395)),
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
