# Generated by Django 3.1.3 on 2020-11-27 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201127_2025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 11, 27, 21, 15, 38, 207691)),
        ),
    ]
