# Generated by Django 3.1.3 on 2020-11-27 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20201127_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 11, 27, 21, 20, 14, 355534)),
        ),
    ]
