# Generated by Django 3.1.3 on 2020-11-27 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 11, 27, 21, 20, 14, 356728)),
        ),
    ]
